### PERTAMBAHAN MATRIKS
POST http://localhost:3000/api/add

{
  "matrixA": [[1,2],[3,4]],
  "matrixB": [[5,6],[7,8]]
}

### PENGURANGAN MATRIKS
POST http://localhost:3000/api/subtract

{
  "matrixA": [[1,2],[3,4]],
  "matrixB": [[5,6],[7,8]]
}

### PERKALIAN MATRIKS
POST http://localhost:3000/api/multiply

{
  "matrixA": [[1,2],[3,4]],
  "matrixB": [[5,6],[7,8]]
}

### TRANSPOSE MATRIKS
POST http://localhost:3000/api/transpose

{
  "matrix": [[1,2],[3,4]]
}

### INVERSE MATRIKS
POST http://localhost:3000/api/inverse

{
  "matrix": [[1,2],[3,4]]
}

### DETERMINAN MATRIKS
POST http://localhost:3000/api/determinan

{
  "matrix": [[1,2],[3,4]]
}

### REDUCE MATRIKS
POST http://localhost:3000/api/reduce

{
  "matrix": [[1,2],[3,4]]
}

### IDENTITY MATRIKS
GET http://localhost:3000/api/create/identity?size=3

### Diagonal MATRIKS
GET http://localhost:3000/api/create/diagonal?size=3&diagonal=5